// <auto-generated />
using System;
using ExpertManagmentSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExpertManagmentSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240524111451_DbUpdateCCFreelegalService")]
    partial class DbUpdateCCFreelegalService
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ExpertUserMngt")
                .HasAnnotation("ProductVersion", "6.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ExpertManagmentSystem.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DepartmentCategory")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Full_Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<Guid>("UserDepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("UserParentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users", "ExpertUserMngt");
                });

            modelBuilder.Entity("ExpertManagmentSystem.Models.CivilCaseModels.CCdlt", b =>
                {
                    b.Property<Guid>("CCdltId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CCDltDecissionTypes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DltAddressWoreda")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DltAddressZone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DltAge")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int>("DltAmountBirr")
                        .HasColumnType("int");

                    b.Property<int>("DltAmountKarie")
                        .HasColumnType("int");

                    b.Property<string>("DltApplicant")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DltAssignto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DltCreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DltCreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DltDeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DltDeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DltDoAss")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DltDoRet")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DltDoo")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DltEdittedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DltExpertName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DltFileNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DltGender")
                        .HasColumnType("int");

                    b.Property<string>("DltLOS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DltRecorNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DltResponder")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DltSupportType")
                        .HasColumnType("int");

                    b.Property<Guid?>("DltUpdatededBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DlttypesofIssue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CCdltId");

                    b.ToTable("CCdlt", "ExpertUserMngt");
                });

            modelBuilder.Entity("ExpertManagmentSystem.Models.CivilCaseModels.CCFreeLegServiceFollowup", b =>
                {
                    b.Property<Guid>("FreeLegServiceFollowupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AppointmentType")
                        .HasColumnType("int");

                    b.Property<Guid>("CCFreelServicesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("DecisionStatus")
                        .HasColumnType("int");

                    b.Property<string>("Decisionmadeby")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DoD")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Doa")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Doc")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FollupCreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("FollupCreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("FollupDeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("FollupDeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("FollupEdittedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("FollupUpdatededBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("FreeLegServiceFollowupId");

                    b.HasIndex("CCFreelServicesId");

                    b.ToTable("CCFreeLegServiceFollowup", "ExpertUserMngt");
                });

            modelBuilder.Entity("ExpertManagmentSystem.Models.CivilCaseModels.CCFreelServices", b =>
                {
                    b.Property<Guid>("CCFreelServicesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AddressWoreda")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressZone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("AmountinBirr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AmountinOther")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Amountincarie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Applicant")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CCPDecissionStatus")
                        .HasColumnType("int");

                    b.Property<int?>("CCPDecissionTypes")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CCServCreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CCServCreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CCServDeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CCServDeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CCServEdittedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CCServUpdatededBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("CustomerCategory")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DoAss")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DoRet")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Doo")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("ExpertName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FreelCategory")
                        .HasColumnType("int");

                    b.Property<int?>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("LOS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecorNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Responder")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SectrorsDepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("SupportType")
                        .HasColumnType("int");

                    b.Property<int>("typesofIssue")
                        .HasColumnType("int");

                    b.HasKey("CCFreelServicesId");

                    b.HasIndex("SectrorsDepartmentId");

                    b.ToTable("CCFreelServices", "ExpertUserMngt");
                });

            modelBuilder.Entity("ExpertManagmentSystem.Models.CivilCaseModels.CCLegaladvices", b =>
                {
                    b.Property<Guid>("CCLegaladvicesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CCLadDecissionTypes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LadAddressWoreda")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LadAddressZone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LadAmountBirr")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("LadAmountKarie")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("LadAssignto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LadCreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LadCreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LadDaos")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LadDeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LadDeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LadDoare")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LadDoariv")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LadEdittedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LadExpertName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LadFileNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LadTimeTaken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LadTypes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("LaddatededBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ladvicerequester")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CCLegaladvicesId");

                    b.ToTable("CCLegaladvices", "ExpertUserMngt");
                });

            modelBuilder.Entity("ExpertManagmentSystem.Models.CivilCaseModels.CCPetition", b =>
                {
                    b.Property<Guid>("CCPetitionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CCPeDecissionTypes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PeAddressWoreda")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PeAddressZone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PeAge")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("PeAssignto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PeCreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("PeCreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("PeDaos")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PeDeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("PeDeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("PeDoare")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PeDoariv")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PeEdittedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PeExpertName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PeFileNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PeGender")
                        .HasColumnType("int");

                    b.Property<int>("PeSupportType")
                        .HasColumnType("int");

                    b.Property<string>("PeTimeTaken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PeTypes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PeUpdatededBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Pevicerequester")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CCPetitionId");

                    b.ToTable("CCPetition", "ExpertUserMngt");
                });

            modelBuilder.Entity("ExpertManagmentSystem.OrganizationalStructures.ReginalSector", b =>
                {
                    b.Property<Guid>("ReginalSectorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReginalSectorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReginalSectorId");

                    b.ToTable("ReginaslSector", "ExpertUserMngt");
                });

            modelBuilder.Entity("ExpertManagmentSystem.OrganizationalStructures.SectrorsDepartment", b =>
                {
                    b.Property<Guid>("SectrorsDepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DepartmentCategory")
                        .HasColumnType("int");

                    b.Property<string>("DepartmentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DepartmentParentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SectrorsDepartmentId");

                    b.ToTable("SectrorsDepartment", "ExpertUserMngt");
                });

            modelBuilder.Entity("ExpertManagmentSystem.OrganizationalStructures.WoredaSectors", b =>
                {
                    b.Property<Guid>("WoredaSectorsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("WoredaSectorsName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ZonalSectorsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("WoredaSectorsId");

                    b.HasIndex("ZonalSectorsId");

                    b.ToTable("WoredaSectors", "ExpertUserMngt");
                });

            modelBuilder.Entity("ExpertManagmentSystem.OrganizationalStructures.ZonalSectors", b =>
                {
                    b.Property<Guid>("ZonalSectorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ReginalSectorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ZonalSectorName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ZonalSectorId");

                    b.HasIndex("ReginalSectorId");

                    b.ToTable("ZonalSectors", "ExpertUserMngt");
                });

            modelBuilder.Entity("ExpertManagmentSystem.ViewModels.CivilCaseViewModels.CCFreeLsfuViewModel", b =>
                {
                    b.Property<string>("AddressWoreda")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressZone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Applicant")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AppointmentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CCFreelServicesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("DecisionStatus")
                        .HasColumnType("int");

                    b.Property<string>("Decisionmadeby")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DoAss")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DoD")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DoRet")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Doa")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Doc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Doo")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExpertName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FreeLegServiceFollowupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("FreelCategory")
                        .HasColumnType("int");

                    b.Property<int?>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("LOS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PDecission")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecorNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Responder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SectrorsDepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("SupportType")
                        .HasColumnType("int");

                    b.Property<string>("apsm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("typesofIssue")
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("SectrorsDepartmentId");

                    b.ToTable("CCFreeLsfuViewModel", "ExpertUserMngt");
                });

            modelBuilder.Entity("ExpertManagmentSystem.ViewModels.SectorDepartmentViewModels", b =>
                {
                    b.Property<int>("DepartmentCategory")
                        .HasColumnType("int");

                    b.Property<string>("DepartmentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DepartmentParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ReginalSectorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReginalSectorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SectrorsDepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WoredaSectorsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("WoredaSectorsName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ZonalSectorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ZonalSectorName")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("SectorDepartmentViewModels", "ExpertUserMngt");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", "ExpertUserMngt");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", "ExpertUserMngt");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", "ExpertUserMngt");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", "ExpertUserMngt");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", "ExpertUserMngt");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", "ExpertUserMngt");
                });

            modelBuilder.Entity("ExpertManagmentSystem.Models.CivilCaseModels.CCFreeLegServiceFollowup", b =>
                {
                    b.HasOne("ExpertManagmentSystem.Models.CivilCaseModels.CCFreelServices", "CCFreelServices")
                        .WithMany("FreeLegServiceFollowup")
                        .HasForeignKey("CCFreelServicesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CCFreelServices");
                });

            modelBuilder.Entity("ExpertManagmentSystem.Models.CivilCaseModels.CCFreelServices", b =>
                {
                    b.HasOne("ExpertManagmentSystem.OrganizationalStructures.SectrorsDepartment", "SectrorsDepartment")
                        .WithMany("CCFreelServices")
                        .HasForeignKey("SectrorsDepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SectrorsDepartment");
                });

            modelBuilder.Entity("ExpertManagmentSystem.OrganizationalStructures.WoredaSectors", b =>
                {
                    b.HasOne("ExpertManagmentSystem.OrganizationalStructures.ZonalSectors", "ZonalSectors")
                        .WithMany()
                        .HasForeignKey("ZonalSectorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ZonalSectors");
                });

            modelBuilder.Entity("ExpertManagmentSystem.OrganizationalStructures.ZonalSectors", b =>
                {
                    b.HasOne("ExpertManagmentSystem.OrganizationalStructures.ReginalSector", "ReginalSector")
                        .WithMany("ZonalSectors")
                        .HasForeignKey("ReginalSectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReginalSector");
                });

            modelBuilder.Entity("ExpertManagmentSystem.ViewModels.CivilCaseViewModels.CCFreeLsfuViewModel", b =>
                {
                    b.HasOne("ExpertManagmentSystem.OrganizationalStructures.SectrorsDepartment", "SectrorsDepartment")
                        .WithMany()
                        .HasForeignKey("SectrorsDepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SectrorsDepartment");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ExpertManagmentSystem.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ExpertManagmentSystem.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExpertManagmentSystem.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ExpertManagmentSystem.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ExpertManagmentSystem.Models.CivilCaseModels.CCFreelServices", b =>
                {
                    b.Navigation("FreeLegServiceFollowup");
                });

            modelBuilder.Entity("ExpertManagmentSystem.OrganizationalStructures.ReginalSector", b =>
                {
                    b.Navigation("ZonalSectors");
                });

            modelBuilder.Entity("ExpertManagmentSystem.OrganizationalStructures.SectrorsDepartment", b =>
                {
                    b.Navigation("CCFreelServices");
                });
#pragma warning restore 612, 618
        }
    }
}
